export const GET_ALL_MESSAGES_GENERAL = 'GET_ALL_MESSAGES_GENERAL';
export const GET_ALL_MESSAGES_LOCAL = 'GET_ALL_MESSAGES_LOCAL';
export const INSERT_MESSAGE_GENERAL = 'INSERT_MESSAGE_GENERAL';
export const INSERT_MESSAGE_LOCAL = 'INSERT_MESSAGE_LOCAL';

export const ADDED_MESSAGE_GENERAL = 'ADDED_MESSAGE_GENERAL';
export const ADDED_MESSAGE_LOCAL = 'ADDED_MESSAGE_LOCAL';

export const REMOVE_MESSAGE_LOCAL = 'REMOVE_MESSAGE_LOCAL';

export const USER_CONNECTED_GENERAL = 'USER_CONNECTED';
export const USER_CONNECTED_LOCAL = 'USER_CONNECTED_LOCAL';

export const USER_DISCONNECTED_LOCAL = 'USER_DISCONNECTED_LOCAL';
